### PR TITLE
Add update-notifier

### LINKED ISSUE #91: Add update-notifier to prompt users of new updates.
#### Tell us about the issue you are experiencing
Improve uptake of the latest version of Astrum.

#### What behaviour would you expect?
If a new version of Astrum is available an update prompt will be presented when people use it.

### PR DESCRIPTION
**Pull request by mischah**
Closes #91

#### What does this PR cover?

Add Update notification for whenever a new versions is released in a non-intrusive way.
Via https://github.com/yeoman/update-notifier

#### How can this be tested?

Set an old version in the `package.json` of the locally linked npm module.
See https://github.com/yeoman/update-notifier/blob/master/example.js

#### Screenshots / Screencast
image

#### What gif best describes how you feel about this work?
gif

---

#### Reviewers

**Review 1**
- [ ] :+1:

**Review 2** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.

---

### CODE REVIEW

**Comment by mischah** [comment]
I guess `release/2.0.0` is the correct branch, right?

**Comment by RyanHavoc** [comment]
Thanks @mischah!

**Comment by krnlde** [comment]
Best. Gif. Ever.

**Comment by mischah** [comment]
My pleasure.

@krnlde Jup 😆

**Pull request merged**
