### PR TITLE
New feature: hide code sample

### LINKED ISSUE #26: FAQ: Is it possible to disable preview of code and just show code sample?
#### Tell us about the issue you are experiencing

I want to use the framework to do patterns für Templating-Code of an CMS. There are CMS-Variables in the code so that there is no possibility to show a preview.
#### What behaviour would you expect?

I expect an parameter like "show_component_preview" to define wheter there is a preview or not. Also it would be nice to set "show code" for default.
#### Your environment

Platform: Windows 
OS Version: 10
Node Version: 5.11
NPM Version: 3.8.6
Astrum Version: 1.5.12

BG
Thomas

### PR DESCRIPTION
**Pull request by danielfilho**
#### What does this PR cover?

This PR introduces a new feature listed on the roadmap: hide code sample

I'm pretty sure this implementation isn't the best/most correct, but I'd be glad to have input from you to make it better.

Another question: how're you minifying `main.js` into `main.min.js`? I still need to do this but not sure how you're doing it 😦 

Fix #26

#### How can this be tested?

You can run `astrum new group/component` or `astrum edit group/component`. The question about hiding code sample will come right after the one about apply a dark background.

#### Screenshots / Screencast
screen_shot_2016-08-01_at_17_45_14

pasted_image_01_08_16_17_48

#### What gif best describes how you feel about this work?
success

---

#### Reviewers

**Review 1**
- [ ] :+1:

**Review 2** _(optional)_
- [ ] :+1:

> *(with github reactions this might not make sense anymore, right? 😁 )*

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.

---

### CODE REVIEW

**Comment by RyanHavoc** [comment]
@danielfilho It's pretty close. Thanks for the work!

With regards to minification currently we're just doing it manually: [https://javascript-minifier.com/](https://javascript-minifier.com/)

With regards to feedback, I think the component option should be `disable_code_sample`. This may seem a bit nit-picky but I think it makes the most sense from clarity point of view. The toggle for the components is "Show/Hide Code Sample" so having a `hide_code_sample` option might be confusing as they're hidden by default. Disabling a code sample is a bit clearer and more easily explained in the README.md e.g.:

`Don't display the component code sample.`

Otherwise I'm happy with the PR and if you make those changes I'll merge it. 😀

**Comment by danielfilho** [comment]
thanks for the feedback, @RyanHavoc. just made the changes. lmk if you need something else or everything is ok :)

**Comment by RyanHavoc** [comment]
@danielfilho Great. I'll pull this down and have a quick test as soon as I can.

**Comment by danielfilho** [comment]
just in case: merged master back, solved conflicts and regenerated minified with changes from master :)

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;f5EpCotN&#x2F;15-facility-to-disabled-sample-previews-an-auto-show-code-samples"> Facility to disabled sample previews an auto show code samples.</a>

**Pull request closed without merging**
