### PR TITLE
Configurable components folder location.

### PR DESCRIPTION
**Pull request by anders0l**
We are including your pattern library to ITCSS structure. We named folder's like 
01-settings
02-sass-tools
03-generic
04-elements
05-layout
06-components
07-utilities
And we need to rename "components" to "06-components" folder in your lib.
This is simple solution, that we already used.

### CODE REVIEW

**Comment by RyanHavoc** [comment]
@anders0l That's fine the only issue is you're setting the folder on the `data` object in main.js directly. This file will be overwritten whenever you update Astrum to a newer version. If you'd be happy to make the following changes and set this PR to merge is `release/2.0.0` branch I'll merge it in:

1) Add a section to `data.json` with key `settings`:
```
"settings": {
    "components_folder": "components"
}
```
2) Add the same structure to the `data` object in `main.js`:
```
data: {
    ...
    settings: {
        components_folder: null
    }
}
```
3) Change your code on line 614 to:
```
group_path = './' + _this.settings.components_folder + '/' + group.name;
```

This way the folder name is stored in `data.json` which is never overwritten. All the values in `data.json` are applied the `data` object when the `initData()` method is called.

Does that make sense?

**Comment by anders0l** [comment]
@RyanHavoc, thank you for the fast reply!
I'm already predefined the folder name in data.json.
like
```
{
...
    "client_url": null,
    "components_folder": "06-components",
    "creators": [
...
}
```
Same code as yours, but **not** inside settings.

The main thing, why I set in **data** `components_folder: "components"` but not `components_folder: null` is that you don't need to predefined folder in data.json if you are using normal structure.

And i didn't find any suitable keys for settings =)

**Comment by RyanHavoc** [comment]
@anders0l Yeah that makes sense. The reason I want it to be in a settings object is so that `data.json` is organised into proper areas of concern rather than a random settings option appearing in a section like `theme` or `creators`.

Last thing, if you could switch this over to `release/2.0.0` for merging that would be good. 2.0.0 has been upgraded to Vue 2.0, I don't think there'll be any breakages but if anything comes up you should be able to make the adjustments.

**Comment by anders0l** [comment]
That makes sense.

And one more benefit - you can change your components location, just by changing components_folder to "../06-components".

No conflicts. You can merge.

Thank you for the great lib!

**Pull request merged**
