### PR TITLE
Fix json example for creating color component

### PR DESCRIPTION
**Pull request by brendastorer**
Adds in some commas that were missing in a console.log json example.

### CODE REVIEW

**Comment by RyanHavoc** [comment]
There's a, minor but annoying, underline issue here. The documentation is a direct copy an paste from the command-line output and although the comma's are in the console.logs as you can see:

https://github.com/NoDivide/astrum/blob/master/manager/astrum-new.js#L158

They're not being output. The comma's drop off... @matt-west you ever seen this happen before?

**Comment by matt-west** [comment]
@RyanHavoc The commas are appearing in the output for me. This PR added them in as they weren't present before.

screen shot 2016-07-04 at 08 39 22

**Comment by RyanHavoc** [comment]
@matt-west Ah of course. Apologies, I thought this was a documentation update. All is well. Thanks @brendastorer.

**Comment by brendastorer** [comment]
@matt-west @RyanHavoc Anytime!

**Pull request merged**
