### PR TITLE
Missing dash on component type docs

### PR DESCRIPTION
**Pull request by mec**
Us copy and paste learners where being tripped up on this.

### CODE REVIEW

**Comment by RyanHavoc** [comment]
It's the damn auto-formatter! I've made this change directly on master has it occurs in several other places as well.

**Comment by mec** [comment]
Amazing! It's a blinding piece of work, congrats! 👍  Been looking at lots of pattern/style guides things and this really stood out!

Thank you so much!

**Comment by RyanHavoc** [comment]
@mec Thank you for saying! 😀 If you don't mind me asking what made Astrum win out over others for you?

**Comment by mec** [comment]
@RyanHavoc Hmmm, well my shopping list was:
- markdown support
- shows markup
- shows css
- served flat
- fits my fu
- looks good to clients

So it was close and very, very polished.

I'm really interested in a kind of pattern library/style guide/brand guideline hybrid for client's digital projects that we can build into our workflow - this fits that bill pretty closely.

I'd love to see a few things that would make it ever better for me, more --types would be good (I suspect they're coming!?), my immediate thought is a favicon one that shows the icon at various sizes with the correct markup in the markup preview. 

It would be nice to have a couple more layout options as well (half, third, quarter, etc) and a way to force them to behave like blocks when I want them too - I'll open a feature request and maybe see if I can see a way to do it?

Thanks again for the effort - mind blowing! 💯

**Comment by RyanHavoc** [comment]
@mec Thanks for the feedback. New types are coming, the favicon component is an interesting idea. We have lots of improvements we want to roll into Astrum so it will continue to get better over time.

**Pull request closed without merging**
